services:
  - type: web
    name: bomboclatt-bot
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
